language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.4
      os: osx
os:
  - linux
  - osx
sudo: false
after_success:
  - bundle exec codeclimate-test-reporter
